frr version 10.6.1
frr defaults traditional
hostname leaf1
log syslog informational
no ipv6 forwarding
!
interface lo
 ip address 10.255.0.11/32
!
interface eth1
 ip address 10.0.1.1/31
 description to-spine1
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.1.7/31
 description to-spine2
 ip ospf network point-to-point
!
interface eth3
 ip address 192.168.1.1/24
 description to-host1
!
router ospf
 ospf router-id 10.255.0.11
 passive-interface eth3
 network 10.255.0.11/32 area 0
 network 10.0.1.0/31 area 0
 network 10.0.1.6/31 area 0
 network 192.168.1.0/24 area 0
!
