frr version 10.6.1
frr defaults traditional
hostname spine1
log syslog informational
no ipv6 forwarding
!
interface lo
 ip address 10.255.0.1/32
!
interface eth1
 ip address 10.0.1.0/31
 description to-leaf1
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.1.2/31
 description to-leaf2
 ip ospf network point-to-point
!
interface eth3
 ip address 10.0.1.4/31
 description to-leaf3
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.1
 network 10.255.0.1/32 area 0
 network 10.0.1.0/31 area 0
 network 10.0.1.2/31 area 0
 network 10.0.1.4/31 area 0
!
