frr version 10.6.1_git
frr defaults traditional
hostname leaf1
log syslog informational
no ipv6 forwarding
!
interface eth1
 description to-spine1
 ip address 10.0.1.1/31
exit
!
interface eth2
 description to-spine2
 ip address 10.0.1.7/31
exit
!
interface eth3
 description to-host1
 ip address 192.168.80.1/24
exit
!
interface lo
 ip address 10.255.0.11/32
exit
!
router bgp 65083
 bgp router-id 10.255.0.11
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.0.1.0 remote-as 65081
 neighbor 10.0.1.0 description spine1
 neighbor 10.0.1.0 bfd
 neighbor 10.0.1.6 remote-as 65082
 neighbor 10.0.1.6 description spine2
 neighbor 10.0.1.6 bfd
 !
 address-family ipv4 unicast
  network 10.255.0.11/32
  network 192.168.80.0/24
  neighbor 10.0.1.0 activate
  neighbor 10.0.1.6 activate
 exit-address-family
exit
!
