frr version 10.6.1
frr defaults traditional
hostname leaf1
log syslog informational
no ipv6 forwarding
!
interface lo
 ip address 10.255.0.11/32
!
interface eth1
 ip address 10.0.1.1/31
 description to-spine1
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.1.7/31
 description to-spine2
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.11
 network 10.255.0.11/32 area 0
 network 10.0.1.0/31 area 0
 network 10.0.1.6/31 area 0
!
router bgp 65080
 bgp router-id 10.255.0.11
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 neighbor 10.255.0.1 remote-as 65080
 neighbor 10.255.0.1 description spine1-rr
 neighbor 10.255.0.1 update-source lo
 neighbor 10.255.0.2 remote-as 65080
 neighbor 10.255.0.2 description spine2-rr
 neighbor 10.255.0.2 update-source lo
 !
 address-family l2vpn evpn
  neighbor 10.255.0.1 activate
  neighbor 10.255.0.2 activate
  advertise-all-vni
 exit-address-family
!
