frr version 10.6.1
frr defaults traditional
hostname spine2
log syslog informational
no ipv6 forwarding
!
interface lo
 ip address 10.255.0.2/32
!
interface eth1
 ip address 10.0.1.6/31
 description to-leaf1
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.1.8/31
 description to-leaf2
 ip ospf network point-to-point
!
interface eth3
 ip address 10.0.1.10/31
 description to-leaf3
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.2
 network 10.255.0.2/32 area 0
 network 10.0.1.6/31 area 0
 network 10.0.1.8/31 area 0
 network 10.0.1.10/31 area 0
!
