frr version 10.6.1_git
frr defaults traditional
hostname bleaf
log syslog informational
no ipv6 forwarding
!
ip route 0.0.0.0/0 10.202.255.254
!
interface eth1
 description to-spine1
 ip address 10.0.1.13/31
exit
!
interface eth2
 description to-spine2
 ip address 10.0.1.15/31
exit
!
interface eth3
 description to-campus
 ip address 10.202.8.253/16
exit
!
interface lo
 ip address 10.255.0.20/32
exit
!
router bgp 65080
 bgp router-id 10.255.0.20
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.0.1.12 remote-as 65081
 neighbor 10.0.1.12 description spine1
 neighbor 10.0.1.12 bfd
 neighbor 10.0.1.14 remote-as 65082
 neighbor 10.0.1.14 description spine2
 neighbor 10.0.1.14 bfd
 neighbor 10.202.0.227 remote-as 65014
 neighbor 10.202.0.227 description campus-as65014
 neighbor 10.202.1.12 remote-as 65001
 neighbor 10.202.1.12 description campus-as65001
 neighbor 10.202.7.253 remote-as 65070
 neighbor 10.202.7.253 description campus-as65070
 neighbor 10.202.8.205 remote-as 65899
 neighbor 10.202.8.205 description valentin-bleaf
 neighbor 10.202.60.22 remote-as 65060
 neighbor 10.202.60.22 description campus-as65060
 !
 address-family ipv4 unicast
  network 10.255.0.20/32
  neighbor 10.0.1.12 activate
  neighbor 10.0.1.12 default-originate
  neighbor 10.0.1.14 activate
  neighbor 10.0.1.14 default-originate
  neighbor 10.202.0.227 activate
  neighbor 10.202.1.12 activate
  neighbor 10.202.7.253 activate
  neighbor 10.202.8.205 activate
  neighbor 10.202.60.22 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.202.8.205 activate
  advertise-all-vni
  vni 570100
   rd 10.255.0.20:570
   route-target import 65899:570
   route-target export 65080:570
   route-target export 65899:570
  exit-vni
  vni 560100
   rd 10.255.0.20:560
   route-target import 65899:560
   route-target export 65080:560
   route-target export 65899:560
  exit-vni
  advertise-default-gw
  advertise-svi-ip
 exit-address-family
exit
!
