all:
  children:
    containerlab_hosts:
      hosts:
        vm220:
          ansible_host: 10.202.8.220
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        vm221:
          ansible_host: 10.202.8.221
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
