---
# Usage: ansible-playbook playbooks/destroy-topo.yml -e "topo=topo-ebgp"
#        ansible-playbook playbooks/destroy-topo.yml -e "topo=vxlan-lab3 target=vm221"
- name: Destroy containerlab topology
  hosts: "{{ target | default('vm220') }}"
  vars:
    topo: "topo-ebgp"
  tasks:
    - name: Destroy topology
      ansible.builtin.command:
        cmd: containerlab destroy -t /root/{{ topo }}/topology.clab.yml --cleanup
      changed_when: true
