frr version 10.6.1
frr defaults traditional
hostname spine1
log syslog informational
no ipv6 forwarding
!
interface lo
 ip address 10.255.0.1/32
!
interface eth1
 ip address 10.0.1.0/31
 description to-leaf1
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.1.2/31
 description to-leaf2
 ip ospf network point-to-point
!
interface eth3
 ip address 10.0.1.4/31
 description to-leaf3
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.1
 network 10.255.0.1/32 area 0
 network 10.0.1.0/31 area 0
 network 10.0.1.2/31 area 0
 network 10.0.1.4/31 area 0
!
router bgp 65080
 bgp router-id 10.255.0.1
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.255.0.11 remote-as 65080
 neighbor 10.255.0.11 description leaf1
 neighbor 10.255.0.11 update-source lo
 neighbor 10.255.0.11 route-reflector-client
 neighbor 10.255.0.12 remote-as 65080
 neighbor 10.255.0.12 description leaf2
 neighbor 10.255.0.12 update-source lo
 neighbor 10.255.0.12 route-reflector-client
 neighbor 10.255.0.13 remote-as 65080
 neighbor 10.255.0.13 description leaf3
 neighbor 10.255.0.13 update-source lo
 neighbor 10.255.0.13 route-reflector-client
 !
 address-family ipv4 unicast
  network 10.255.0.1/32
  neighbor 10.255.0.11 activate
  neighbor 10.255.0.12 activate
  neighbor 10.255.0.13 activate
 exit-address-family
!
