#!/bin/sh
#
# Add static routes (usually IPv4 routes pointing to the first usable gateway)
#
#
echo Removing existing IPv4 routes
while ip route del 0.0.0.0/0 2>/dev/null; do
  : ; done
#
#
#
echo Adding direct static routes
ip route add 0.0.0.0/0 via 10.255.11.1 dev eth1 protocol static
