all:
  hosts: {}
custom_configs:
  hosts:
    bleaf: {}
    leaf1: {}
    leaf2: {}
    spine1: {}
    spine2: {}
daemons:
  hosts: {}
eos:
  hosts:
    bleaf:
      ansible_host: 192.168.121.106
      id: 6
    leaf1:
      ansible_host: 192.168.121.103
      id: 3
    leaf2:
      ansible_host: 192.168.121.104
      id: 4
    leaf3:
      ansible_host: 192.168.121.105
      id: 5
    spine1:
      ansible_host: 192.168.121.101
      id: 1
    spine2:
      ansible_host: 192.168.121.102
      id: 2
leafs:
  hosts:
    bleaf: {}
    leaf1: {}
    leaf2: {}
    leaf3: {}
linux:
  hosts:
    grafana:
      ansible_host: clab-life-grafana
      id: 7
    librespeed:
      ansible_host: clab-life-librespeed
      id: 12
    nginx1:
      ansible_host: clab-life-nginx1
      id: 10
    nginx2:
      ansible_host: clab-life-nginx2
      id: 11
    prometheus:
      ansible_host: clab-life-prometheus
      id: 8
    remotedesktop:
      ansible_host: clab-life-remotedesktop
      id: 13
    sflowrt:
      ansible_host: clab-life-sflowrt
      id: 9
modules:
  hosts:
    bleaf: {}
    grafana: {}
    leaf1: {}
    leaf2: {}
    leaf3: {}
    librespeed: {}
    nginx1: {}
    nginx2: {}
    prometheus: {}
    remotedesktop: {}
    sflowrt: {}
    spine1: {}
    spine2: {}
monitoring:
  hosts:
    grafana: {}
    prometheus: {}
    sflowrt: {}
netlab_no_collect:
  hosts:
    grafana: {}
    librespeed: {}
    nginx1: {}
    nginx2: {}
    prometheus: {}
    remotedesktop: {}
    sflowrt: {}
netlab_no_reload:
  hosts:
    grafana: {}
    librespeed: {}
    nginx1: {}
    nginx2: {}
    prometheus: {}
    remotedesktop: {}
    sflowrt: {}
netlab_normalize:
  hosts:
    bleaf: {}
    leaf1: {}
    leaf2: {}
    leaf3: {}
    spine1: {}
    spine2: {}
netlab_ready_ssh:
  hosts:
    bleaf: {}
    leaf1: {}
    leaf2: {}
    leaf3: {}
    spine1: {}
    spine2: {}
spines:
  hosts:
    spine1: {}
    spine2: {}
unprovisioned:
  children: {}
  hosts: {}
