# frr version 10.6.1_git
# frr defaults traditional
# hostname spine2
# log syslog informational
# no ipv6 forwarding
# !
# ip prefix-list DENY-UNDERLAY seq 5 deny 10.0.1.0/24 le 32
# ip prefix-list DENY-UNDERLAY seq 10 permit 0.0.0.0/0 le 32
# !
# interface eth1
#  description to-leaf1
#  ip address 10.0.1.6/31
# exit
# !
# interface eth2
#  description to-leaf2
#  ip address 10.0.1.8/31
# exit
# !
# interface eth3
#  description to-leaf3
#  ip address 10.0.1.10/31
# exit
# !
# interface eth4
#  description to-bleaf
#  ip address 10.0.1.14/31
# exit
# !
# interface lo
#  ip address 10.255.0.2/32
# exit
# !
# router bgp 65082
#  bgp router-id 10.255.0.2
#  bgp log-neighbor-changes
#  no bgp ebgp-requires-policy
#  no bgp default ipv4-unicast
#  neighbor 10.0.1.7 remote-as 65083
#  neighbor 10.0.1.7 description leaf1
#  neighbor 10.0.1.7 bfd
#  neighbor 10.0.1.9 remote-as 65084
#  neighbor 10.0.1.9 description leaf2
#  neighbor 10.0.1.9 bfd
#  neighbor 10.0.1.11 remote-as 65085
#  neighbor 10.0.1.11 description leaf3
#  neighbor 10.0.1.11 bfd
#  neighbor 10.0.1.15 remote-as 65080
#  neighbor 10.0.1.15 description bleaf
#  neighbor 10.0.1.15 bfd
#  !
#  address-family ipv4 unicast
#   network 10.255.0.2/32
#   neighbor 10.0.1.7 activate
#   neighbor 10.0.1.9 activate
#   neighbor 10.0.1.11 activate
#   neighbor 10.0.1.15 activate
#   neighbor 10.0.1.15 prefix-list DENY-UNDERLAY in
#  exit-address-family
# exit
# !
frr version 10.6.1_git
frr defaults traditional
hostname spine2
log syslog informational
no ipv6 forwarding
!
ip prefix-list DENY-UNDERLAY seq 5 deny 10.0.1.0/24 le 32
ip prefix-list DENY-UNDERLAY seq 10 permit 0.0.0.0/0 le 32
!
interface eth1
 description to-leaf1
 ip address 10.0.1.6/31
exit
!
interface eth2
 description to-leaf2
 ip address 10.0.1.8/31
exit
!
interface eth3
 description to-leaf3
 ip address 10.0.1.10/31
exit
!
interface eth4
 description to-bleaf
 ip address 10.0.1.14/31
exit
!
interface eth5
 description to-leaf4
 ip address 10.0.1.18/31
exit
!
interface lo
 ip address 10.255.0.2/32
exit
!
router bgp 65082
 bgp router-id 10.255.0.2
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.0.1.7 remote-as 65083
 neighbor 10.0.1.7 description leaf1
 neighbor 10.0.1.7 bfd
 neighbor 10.0.1.9 remote-as 65084
 neighbor 10.0.1.9 description leaf2
 neighbor 10.0.1.9 bfd
 neighbor 10.0.1.11 remote-as 65085
 neighbor 10.0.1.11 description leaf3
 neighbor 10.0.1.11 bfd
 neighbor 10.0.1.15 remote-as 65080
 neighbor 10.0.1.15 description bleaf
 neighbor 10.0.1.15 bfd
 neighbor 10.0.1.19 remote-as 65086
 neighbor 10.0.1.19 description leaf4
 neighbor 10.0.1.19 bfd
 !
 address-family ipv4 unicast
  network 10.255.0.2/32
  neighbor 10.0.1.7 activate
  neighbor 10.0.1.9 activate
  neighbor 10.0.1.11 activate
  neighbor 10.0.1.15 activate
  neighbor 10.0.1.15 prefix-list DENY-UNDERLAY in
  neighbor 10.0.1.19 activate
 exit-address-family
exit
!